### ISSUE TITLE
travis-CI does not work properly

### ISSUE THREAD

**Issue by mcgivrer** [SnapGames/singleclassgame#5]
**Describe the bug**
Missing the Travis-CI configuration file `.travis.yml`

**Additional context**
Nee to add the following file :

```yml
#
# SnapGames 2018
#
language: java
jdk:
  - oraclejdk8
#before_install:
#  - Commands toi execute before install
```
